### ISSUE TITLE
Prediction fails when no out_table is given

### ISSUE THREAD

**Issue by mplpl** [IBM/nzpyida#65]
I'm using the DecisionTreeClassifier class and whenever I call predict inside of AutoReleaseContext without giving out_table value, the call fails with the following exception:

```
AttributeError                            Traceback (most recent call last)
Cell In[5], line 4
      2 from nzpyida.analytics import AutoDeleteContext
      3 with AutoDeleteContext(idadb):
----> 4     res_df = model.predict(in_df=pred_df) 
      5     res_df[res_df['CLASS']==1]['ID'].as_dataframe().to_csv('suspected_sim_boxes.csv', header=False, index=False)

File [~/Documents/work/nzpyida/nzpyida/analytics/predictive/decision_trees.py:232](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/analytics/predictive/decision_trees.py:232), in DecisionTreeClassifier.predict(self, in_df, out_table, id_column, prob, out_table_prob)
    196 """
    197 Makes predictions based on this model. The model must exist.
    198 
   (...)
    223     the data frame containing row identifiers and predicted target values
    224 """
    226 params = {
    227     'id': id_column,
    228     'prob': prob,
    229     'outtableprob': out_table_prob
    230 }
--> 232 return self._predict(in_df=in_df, params=params, out_table=out_table)

File [~/Documents/work/nzpyida/nzpyida/analytics/predictive/predictive_modeling.py:111](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/analytics/predictive/predictive_modeling.py:111), in PredictiveModeling._predict(self, in_df, params, out_table)
    108     raise TypeError("Argument in_df should be an IdaDataFrame")
    110 params['model'] = self.model_name
--> 111 return call_proc_df_in_out(proc=self.predict_proc, in_df=in_df, params=params,
    112     out_table=out_table)[0]

File [~/Documents/work/nzpyida/nzpyida/analytics/utils.py:127](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/analytics/utils.py:127), in call_proc_df_in_out(proc, in_df, params, out_table, copy_indexer)
    124 if not isinstance(in_df, IdaDataFrame):
    125     raise TypeError("Argument in_df should be an IdaDataFrame")
--> 127 if in_df._idadb.exists_table_or_view(out_table):
    128         in_df._idadb.drop_table(out_table)
    130 temp_view_name, need_delete = materialize_df(in_df)

File [~/Documents/work/nzpyida/nzpyida/base.py:732](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/base.py:732), in IdaDataBase.exists_table_or_view(self, objectname)
    705 def exists_table_or_view(self, objectname):
    706     """
    707     Check if a table or view exists in self.
    708 
   (...)
    730     TypeError : "NO_TABLE_NOR_VIEW" exists in schema '?' but of type '?'
    731     """
--> 732     return self._exists(objectname,['T', 'V'])

File [~/Documents/work/nzpyida/nzpyida/base.py:1810](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/base.py:1810), in IdaDataBase._exists(self, objectname, typelist)
   1801 def _exists(self, objectname, typelist):
   1802     """
   1803     Check if an object of a certain type exists in Db2 Warehouse.
   1804 
   (...)
   1808     exists_view functions.
   1809     """
-> 1810     objectname = nzpyida.utils.check_tablename(objectname)
   1812     tablelist = self.show_tables(show_all=True)
   1813     schema, name = self._get_name_and_schema(objectname)

File [~/Documents/work/nzpyida/nzpyida/utils.py:218](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/utils.py:218), in check_tablename(tablename)
    198 def check_tablename(tablename):
    199     """
    200     Check if a string is upper case. This function converts the string to upper 
    201     case and checks if it is a valid table name.
   (...)
    216         be separated by underscores (“_”) characters.
    217     """
--> 218     return _check_database_objectname(tablename, 'Table')

File [~/Documents/work/nzpyida/nzpyida/utils.py:268](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/utils.py:268), in _check_database_objectname(tablename, objecttype)
    245 def _check_database_objectname(tablename, objecttype):
    246     """
    247     Check if a string is upper case. This function converts the string to upper
    248     case and checks if it is a valid database object (table, view or model) name.
   (...)
    266         be separated by underscores (“_”) characters.
    267     """
--> 268     tablename = _check_case(tablename)
    269     if not all([(char.isalnum() | (char == '_') | (char == '.')) for char in tablename]):
    270         raise ValueError("%s name '%s' is not valid, only alphanumeric characters and underscores are allowed."%(objecttype, tablename))

File [~/Documents/work/nzpyida/nzpyida/utils.py:240](https://file+.vscode-resource.vscode-cdn.net/Users/mpl/Documents/work/~/Documents/work/nzpyida/nzpyida/utils.py:240), in _check_case(name)
    235 def _check_case(name):
    236     """
    237     Check if the name given as parameter is in upper case and convert it to 
    238     upper cases.
    239     """
--> 240     if name != name.upper():
    241         warnings.warn("Mixed case names are not supported in database object names.", UserWarning)
    242     return name.upper()

AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by mplpl** [comment]
This is a regression caused by https://github.com/IBM/nzpyida/commit/b2123d3c97e8641f13de52f8b3a3423d512bb0c4

**Comment by mplpl** [comment]
@mrozpawel we need to fix this ASAP

**Comment by mplpl** [comment]
Fixed in 0.9.1
